name: Build and Deploy docs

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Build environment
      shell: bash -l {0}
      run: |
         conda create --name build-site -c conda-forge rb-bundler compilers
         source activate build-site
         bundle install
    - name: Build documentation
      shell: bash -l {0}
      run: |
        source activate build-site
        bundle exec jekyll build --verbose

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      if: github.ref == 'refs/heads/source' && github.repository == 'ICESAT-2HackWeek/icesat-2hackweek.github.io'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: _site
        CLEAN: false
